learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# For template tagging
app_name = "basic_app"

urlpatterns = [
    path("other/", views.other, name="other"),
    path("relative/", views.relative, name="relative"),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("", views.index, name="index"),
    path("basic_app/", include("basic_app.urls")),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {"text":"Hello world!", "number":100}
    return render(request, "basic_app/index.html", context_dict)

def other(request):
    return render(request, "basic_app/other.html")

def relative(request):
    return render(request, "basic_app/relative_url_templates.html")

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item active"><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item"><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative</a></li>
                <li class="nav-item"><a class="navbar-link" href="{% url 'basic_app:other'%}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!--Anything outside of this will be inherited if you extend! -->
        {% endblock %}
    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {%block body_block%}
    <h1>Welcome to our new INDEX page!</h1>
    <h2>This is index.html page showing!<h2>
        {{ text | upper}} # This makes it uppercase <br>
        {{ text | cut:"Hello"}} # This cuts out hello <br>
        {{ number | add:"99" }} # This adds 99 <br>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {%block body_block%}
    <h1>Welcome to OTHER!</h1>
    <h2>This is an example of template inheritance!<h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {%block body_block%}
    <h1>Welcome to RELATIVE page!</h1>
    <h2>This is an relative example of template inheritance!<h2>
    {% endblock %}